version: "3"

services:
  nginx:
    restart: on-failure
    build:
      context: nginx/
    ports:
      - "8080:8080"
    depends_on:
      - jib
      - karim
      - frontend

  frontend:
    build:
      context: frontend/

  jib:
    build:
      context: jib/
    depends_on:
      - psql
      - redis

  karim:
    build:
      context: karim/
    depends_on:
      - psql
      - redis

  redis:
    image: redis:5.0-alpine3.8

  psql:
    build:
      context: postgresql/
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@google.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "psql:pgsql-server"
    depends_on:
      - psql

volumes:
  db-data:
  pgadmin-data:
